version: '3'
services:
  markdown-api:
    build:
      context: .
    environment:
      - "NODE_ENV=development"
    ports:
      - "2998:2998"
    volumes:
      - ./:/app
      - node_modules_cache:/app/node_modules
volumes:
  node_modules_cache:
